[build]
  publish = ".next"
  command = "npm run build"
  

  [[plugins]]
  package = "@netlify/plugin-nextjs"

  [[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "https://www.quiltedrose.org/*"
  to = "https://quiltedrose.org/:splat"
  status = 301
  force = true    

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/helpful-resources.html"
  to = "/resources"
  status = 301

[[redirects]]
  from = "/resources.html"
  to = "/resources"
  status = 301

[[redirects]]
  from = "/internships.html"
  to = "/resources"
  status = 301

[[redirects]]
  from = "/our-process.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/aboutUs.html"
  to = "/about"
  status = 301
  
[[redirects]]
  from = "/aboutus.html"
  to = "/about"
  status = 301
  
[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/work-with-dr.walker.html"
  to = "/about"
  status = 301
  
[[redirects]]
  from = "/Why-quiled-rose.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/why-quiled-rose"
  to = "/about"
  status = 301

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contactUs"
  status = 301

