[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/contact"
  to = "/thank-you"
  status = 303
  force = true
