export const pages = {
    home:{
        hero:{title:'Welcome to Quilted Rose' },
        about:{title:'Meet Dr. Lisa Walker', 
                text1:'I\'m Dr. Lisa Walker, a psychologist and licensed mental health counselor (LPC) with more than 20 years of experience. I respect the individual as part of the collective community. I believe that healing or mental health treatment cannot occur alone. Black and Indigenous people heal in community.', 
                text2:'I intentionally serve all Black and Indigenous adults with reverence and compassion. I place a special emphasis on emotionally supporting female-identifying persons who work in the creative, health care, mental health and education fields.',
                text3:'I work collaboratively with individuals navigating the impact of cultural trauma, newly diagnosed adult ADHD (at 30, 40, 50+), disordered eating and complex relationships with food or movement, and the unique experiences of transracial adoptees coming to terms with their upbringing. This space is also open for exploring whatever else you’re ready to unpack—with compassion and care.'},
        vision:{title:'Our Vision', 
                text1:'My vision is to collaborate with Black and Indigenous individuals as we navigate everyday challenges—grief and loss, anxiety, political burnout—along with collective trauma and systemic marginalization. I offer several ways to support and partner with you on this journey:', 
                quote:'“You will be understood and challenged. You will grow and be uncomfortable.” -Dr. Lisa Walker'},
        card1:{title:'Speaking Engagements', 
                text:'Subject matter expert in: trauma informed care implementation, using harm reduction to support eating disorder clients, comprehensively addressing suicide prevention.'},
        card2:{title:'Professional Coaching', 
                text:'Building confidence, career changes later in life, returning to dating after divorce or long-term relationship, finding your purpose, passion, balance.'},
        card3:{title:'Wellness Guides', 
                text:'Based in collective healing and compassion - the 8 domains of wellness will support your evolution, reconnecting your mind - body - spirit, and bring you closer to building \‘community\’ as you define it'},
        cta:{quote:'"You will have breakthroughs and struggle to see progress. I will focus on your strengths even if you do not see any." - Dr. Lisa Walker'},
        belief:{title:'What We Believe', 
                text1:'Quilted Rose was created out of a deep ancestral drive to work inpartnership with Black and Indigenous people as we navigate everyday challenges (grief and loss, anxiety, political burnout), collective trauma and targeted marginalization.',
                text2:'Are you an African, Black American, or Indigenous person looking to incorporate or explore traditional spiritual practices within your mental wellness or coaching journey—in a safe and intentional way? If so, schedule an appointment today in the form below.'},
        contact:{title:'Contact'}
    },
    about:{
        hero:{title:'Meet Dr. Lisa Walker' },
        about:{title:'Founder, Consultant, Speaker',
                text1:'I am Dr. Lisa Walker, a psychologist and licensed mental health counselor (LPC) with more than 20 years of experience', 
                text2:'I believe that healing or "mental health treatment" cannot occur alone. Black and Indigenous people heal in community. Quilted Rose was created out of a deep ancestral drive to work in partnership with Black and Indigenous people as we navigate everyday challenges (grief and loss, anxiety, political burnout), collective trauma and targeted marginalization.', 
                text3:'Working with me may include activities to help you understand where emotions are stored in your body and how to release or expand those emotions, referrals to spiritual healers, and may include referrals to professionals that practice typical western medicine.'},
        values:{title:'My Values',
                subtitle:'Rooted in Black / Original Feminism',
                text1:('Thankfully there is no singular definition of \'feminism\' or what it means to be a \'feminist\'... However, I stand firmly in my understanding of what feminism is <br><span class="abt-acc "> not... </span></br> '), 
                text2:'Non-Black “feminism”; the drive to compete for and with males for dominance. To maintain hierarchical perceived superiority (masked mediocrity).To express unchecked power. To use hyper-stereotypical feminine mannerisms to project victimhood. To deliberately exclude those who do not fit into a narrow mold of eurocentric serpentine femininity while directly benefiting from those excluded “other\’s” actual feminist activism. Often described in \‘waves\’ as it aggressively distances itself from the words and spirit of elder feminist scholar Sojourner Truth.', 
                text3:'Even stronger are my beliefs of what feminism <br><span class="abt-acc">is...</span> </br>', 
                text4:'...rooted in grace, dignity, respect and liberation for all Black and Indigenous women and girls, a profound deep reverence that transcends language and time, a belief that we are all interconnected, allowing for compassion for Black and Indigenous women and girls that may, at times, embody the beliefs and behaviors of the oppressor. Black feminism understands how systems of oppression and power like white supremacy (frail inferiority), patriarchy, capitalism, homophobia, transphobia, ableism, etc are both interrelated and systemic. Thereby enabling a near super-human ability to predict, with surgical precision how, the consequences that those systems actions(ors) today will have on future generations… while everyone else is allowed to feign ignorance.', 
                text5:'There is an expectation for self and community accountability when a segment of Black and Indigenous women or girls are further oppressed or marginalized, (due to SOGIE, physical presentation, parentage, vocal accent and language, neurodiversity, financial access, relationship status, religious or spiritual affiliation, national origin…), where the more tolerated of us must yield space for those with less privilege', 
                text6:'Being a feminist is not just, “being equal to men.” That definition is uninspiring, lacks complexity and is meaningless. So what exactly does being a feminist mean? What does this look like for a regular - degular person? It means we (feminists or if you\’re not comfortable with that word - just good people) understand that our place in the world is to not create systems that harm others - intentionally or not. We are responsible stewards of earth that appreciate nature and work to make sure that we have breathable air, clean water and viable soil. We participate in, or we are discovering, the spiritual practices that fulfill us, not just because it\’s what everyone around us may be practicing. But the spiritual practices that allow our innate powers to soar. ', 
                text7:'We understand that our bodies hold all of our memories. It just trauma. Our bodies hold joy, peace, gratitude... everything Our bodies, if we are, or are willing to be, tuned in, can and will always tell us exactly what we need (rest, food, movement…). And so so so much more. ', 
                text8:'Want to learn how to combat what feminism is <span class="abt-acc underline">not</span>? How to strengthen your true innate feminism? I am here for you to work with through 1-on-1 mental health therapy, professional coaching, speaking engagements, and wellness books. Where would you like to start?'},
        card1:{title:'', text:''},
        card2:{title:'', text:''},
        card3:{title:'', text:''},
        cta:{quote:'"I will focus on your strengths even if you do not see any." - Dr. Lisa Walker'},
    },
    resources:{
        hero:{title:'Resources', 
              text1:'',
              text2:'',
              text3:'', },
        reads:{title:'Recommended Reads' },
        partners:{title:'Community Partners' },
        books:{point1:'Ain\'t I A Woman-Sojourner Truth', 
            point2:'All About Love-Bell Hooks', 
            point3:'Post Traumatic Slave Syndrome -Dr.Joy Degruy', 
            point4:'Women Race and Class-Angela Davis', 
            point5:'Hood Feminism-Mikki Kendall', 
            point6:'Kindred-Octavia E. Butler', 
            point7:'Sister Outsider-Audre Lorde', 
            point8:'Black Feminist Thought-Dr. Patricia Hill Collins', 
            point9:'In Search of Our Mother\’s Gardens: Womanist Prose-Alice Walker ', 
            point10:'Parable of the Sower-Assata Shakur', 
            point11:'Assata: An Autobiography-Audre Lorde',},
        other:{point1:(<a href="https://beam.community/wellness-tools/" target="_blank" className="underline text-darkGreen">'BEAM-Black Emotional and Mental Health Collective'</a>), 
            point2:(<a href="https://www.melaneyesmedia.com/" target="_blank" className="underline text-darkGreen">'Melaneyes Media-Knowledge based Black Films & Video'</a>) },
        cta:{quote:''},
    },
    services:{
        hero:{title:'Services'},
        about:{title:'Therapy',
             text1:'Are you an African, Black American, or Indigenous person looking to integrate traditional spiritual practices into your mental wellness or coaching journey in a safe and intentional way?',
             text2:'When working with me, you are welcomed and encouraged to incorporate or explore traditional spiritual practices (Ifa, ancestral veneration, altar building, vision boards, tarot, crystals, essential oils, astrology) into therapy or coaching',
             text3:'Are you an African, Black American, or Indigenous person looking to integrate traditional spiritual practices into your mental wellness or coaching journey in a safe and intentional way?'},
        bullet:{text1:'My services extend beyond individuals. If you\'re a non-profit organization, corporation, or political office looking for:',
                point1:'General guidance', 
                point2:'Burn out prevention & Recovery', 
                point3:'Staff Retention',
                point4:'Policy and procedures writing', 
                point5:'Grant writing & management (private, federal, state)', 
                point6:'Program development',
                point7:'Project management',
                point8:'Limited Licensed Professional Counselor Supervision',
                point9:'',
                text2:'Feel free to get in touch with me. If you want to discover more ways that we can work together take a look below:'}, 
        cta:{quote:'"It is the mind that makes the body." - Sojourner Truth'},
        other:{title:'Other Ways to Work With Me', 
                text1:''},
        contact:{title:''},
        service1:{heading:'Speaking Engagements', subtitle:'Subject matter expert in: trauma informed care implementation, using harm reduction to support eating disorder clients, comprehensively addressing suicide prevention.'},
        service2:{heading:'Professional Coaching', subtitle:'Building confidence, career changes later in life, returning to dating after divorce or long-term relationship, finding your purpose, passion, balance.'},
        service3:{heading:'Wellness Guides', subtitle:'Based in collective healing and compassion - the 8 domains of wellness will support your evolution, reconnecting your mind - body - spirit, and bring you closer to building \‘community\’ as you define it'},
        service4:{heading:'', subtitle:''},
    },
    privacy:{
        hero:{title:'Privacy Policy' },
        section1:{title:'Consent for Treatment w/ Dr. Lisa Walker, PsyD', text1:'Thank you for choosing (me) Dr. Walker as your therapist. As a client, you have the right to decide if my services are suitable for your needs at any time. This document is designed to inform you about my professional credentials, therapeutic orientation, fee schedule, and your rights as a client. I encourage you to voice any concerns that you may have at any time while we are working together.'},
        policy:{title:'Credentials',
                 text1:'Dr. Walker received her Master\'\s in Counseling from Wayne State University and a doctorate in clinical psychology for The Chicago School of Professional Psychology. She has fifteen years of experience providing therapy to adolescents and adults. Dr. Walker is licensed as a Licensed Professional Counselor in Michigan (LPC# 6401010055)'},
        policy1:{title:'Theoretical Orientation:',
                 text1:'Dr. Walker works with all Black and Indigenous adults; with a special emphasis on those who work in the health care, education and nonprofit sectors. She works collaboratively to facilitate growth in individuals effected by cultural trauma, those newly diagnosed adult ADHD at 30, 40, 50+ years old, disordered eating or have a complicated relationship with food and or movement and those who would like to explore their indigenous / traditional spiritual practices in a safe welcoming space.',
                 text2:'Dr. Walker has worked as a clinician and in leadership positions in private child welfare settings, hospitals, residential, outpatient and criminal justice settings. Dr. Walker is a trauma and recovery specialist (trained TF-CBT (for use with adolescents), BrainSpotting and EMDR), a trained LLPC supervisor and a consultant to organizations providing trauma-informed care and cultural responsibility trainings.'},
        policy2:{title:'Telehealth Therapy:',
                 text1:'Distance counseling has become the norm for many, if not most, client - therapist relationships. To engage in telehealth with Dr. Walker a stable internet connection, email, and a credit/debit card are needed to participate. You must also have your camera on and in a stable location (not driving or in any moving vehicle) throughout the entirety of each session. ',
                 text2:'It is also strongly recommended that you utilize a computer, laptop or tablet as opposed to phone. Finally, it is your responsibility to ensure, on your end, that you are in a location where your session cannot be overheard by others. If you must be in a semi-shared location, headphones are required to increase privacy and to decrease background noise. Before our first meeting, I will provide instructions for connecting to a secure, HIPAAcompliant telehealth platform.'},
        policy3:{title:'Confidentiality:', 
                 text1:'I will keep confidential anything you say as part of our counseling relationship, with the following exceptions:',
                 point1:'You direct Dr. Walker in writing to disclose information to someone else.',
                 point2:'Dr. Walker is ordered by a court to disclose information.',
                 point3:'Abuse of Children or Elderly Persons: If a mental health professional reasonably believes that a child under the age of 18 or an elderly person is being abused or neglected, they are legally obligated to report this situation to the appropriate state agency.',
                 point4:'Imminent Harm to Self: If a mental health professional reasonably believes that you are in imminent danger of physically harming and if you are unwilling or unable to follow treatment recommendations, they may have to make an involuntary referral to a hospital and/or contact a family member or other person who may be able to help protect you.',
                 point5:'Imminent Harm to Others: If a mental health professional reasonably believes that you are an actual threat to the safety of another person, they may be required to take some action (such as contacting the police, notifying the other person, seeking involuntary hospitalization, or some combination of these actions.',
                 },
        policy4:{title:'Dual Relationships:',
                 text1:'The relationship you and Dr. Walker share is a professional one, and should not be confused with a friendship or one of a social nature. It is against any mental health therapist\'\s ethical code to participate in a client\'\s life beyond the professional role before, during, or after the client receives services. In order to protect your privacy as well as that of Dr. Walker, please understand that they cannot accept invitations to social gatherings or social media.',
                 text2:'Together, let\'s discuss a plan for how we will handle accidental run-ins in public. My general rule of thumb is to take your lead in public, and never make first contact in order to respect your privacy. Also, due to ethical guidelines and respect of our working relationship, please understand that Dr. Walker is unable to accept gifts of any kind.'   },
        policy5:{title:'In Case of Emergency:',
                 text1:'Please be aware that Dr. Walker does not have office staff. For routine messages, scheduling, questions, you may leave a message on their confidential voicemail or via the HIPAA complaint messaging platform within SimplePractice. You may choose to use text messaging, but please be aware of the risk of this since it is not guaranteed to be confidential.',
                 text2:'Due to work schedules, Dr. Walker is often not immediately available by telephone. Dr. Walker does not answer the phone during sessions. If you are an existing client Dr. Walker checks for messages frequently and makes every effort to return calls or message within a 24-hour period of your contact, with the exception of weekends and holidays or when she has indicated to being away from the office for extended periods of time.',
                 text3:'Please be aware that email may not be secure. Therefore, only use it for limited purposes such as scheduling and general questions. Please do not include sensitive information in an email and never use it in an emergency. If you have an urgent situation that you feel needs immediate support, please contact one of the following:',
                 point1:'Detroit Mobile Crisis, 313-258-3842',
                 point2:'National Suicide Prevention Lifeline; 1-800-273-TALK (8255)',
                 point3:'LGBTQ Youth Suicide Hotline; 1-866-4-U-TREVOR (487-3867)',
                 point4:'Visit your Primary Care Physician or go to the nearest hospital emergency room.',
                 point5:'Contact emergency services, 988',},
        policy6:{title:'Complaint Procedures:',
                 text1:'The State of Michigan requires counselors to adhere to a specific Code of Conduct that is determined by the Board of Counseling. Please feel free to speak with Dr. Walker directly if you are offended or dissatisfied with any part of your counseling experience so the issues can be address together. Direct, honest communication is an essential component of the therapeutic relationship. Should you wish to file a complaint, you may do so through: Michigan Department of Licensing and Regulatory Affairs Health Professions Division Enforcement Section P.O. Box 30670 Lansing, MI 48909 (517) 373-9196'},
        policy7:{title:'Session Fees and Length of Service:',
                 text1:'My fee for a 50 minute session is $175 each session. No refunds are given if sessions are terminated by the client (either by no-show or discussed termination) prior to the use of pre-paid sessions. Dr. Walker accepts PayPal (paypal.me/quiltedrosecs), HSAs, and all major debit and credit cards directly through the SimplePractice portal. Dr. Walker does raise fees periodically. When there is any change in fees schedule, they will notify you in advance.'},
        policy8:{title:'Insurance:',
                 text1:'Dr. Walker is in network with Blue Cross Blue Shield of MI and Blue Care Network. You are encouraged to call the number on the back of your insurance card to ask about your “out-of-network” benefits, so there aren\'\t any financial surprises. Dr. Walker may provide you with a receipt at the end of each session which you can submit to your insurance company for possible reimbursement. You are responsible for any fees at the time of our appointment, and, depending on your plan, a certain percentage may be paid to you by your insurance company. Upon initiation of the therapeutic relationship Dr. Walker\'\s billing company (Premier Billing) may contact you to verify your behavioral health benefits.'},
        policy9:{title:'Cancellation Policy:',
                 text1:'If you are unable to keep an appointment, please contact (text, email or portal message) Dr. Walker within 24 hours to cancel or reschedule. You will be charged the full fee of $175 for missed appointments unless you cancel or reschedule 24 hours prior to your scheduled appointment. Dr. Walker accepts PayPal (paypal.me/quiltedrosecs), HSAs, and all major debit and credit cards directly through the SimplePractice portal. ',
                 text2:'Dr. Walker will provide a receipt for all fees paid. A fee of $35.00 will be charged for all insufficient funds transfers. Finally, after 2 missed sessions (or if the intake session is missed) you will be removed from Dr. Walker\'\s list of current (active) clients (i.e. you will be discharged from services with Quilted Rose Clinical Services, PLLC). You will receive a final bill for any unpaid services as well as referral options.',
                 text3:'Services will be rendered in a professional manner consistent with ethical standards. It is impossible to guarantee any specific results regarding your counseling goals as the outcome is dependent on the largely unpredictable nature of behavioral health care. However, together we will work to achieve the best possible results. Referral to another counselor or service will be mutually discussed if progress is not achieved at a satisfactory level or in the event that additional services may be in your best interest.'},
    },
    faq:{
        hero:{title:'Frequently Asked Questions' },
        header:{title:'Before Getting Started with Quilted Rose', text1:'Take a look at our FAQ below:'},
        faq1:{heading:'What is the length and frequency of our sessions?', subtitle:'50 minutes typically once a week'},
        faq2:{heading:'Are the sessions virtual or in person?', subtitle:'All sessions are virtual'},
        faq3:{heading:'Do you bill insurance?', subtitle:'We no longer accept any form of insurance. All payments are due at the time of service.'},
        faq4:{heading:'What are your privacy practices?', subtitle: (
                <>Our privacy policy can be found <a href="/privacy-policy" className="text-sage underline font-bold">here</a>.</>
              ) },
        cta:{quote:'“Taking care of other people can be a cure for nightmares.” - Octavia Butler'},
    },
    offer:{
        hero:{title:'Journey To Wellness Workbook-Coming Soon' },
        section1:{title:'Discover the 8 Domains of Wellness!',
                text1:'Explore the key areas of well-being—Emotional, Environmental, Financial, Intellectual, Physical, Occupational, Social, and Spiritual.', 
                text2:'Gain insights into each domain and take the first step toward a balanced, healthier life.', 
                text3:''},
                section2: {
                        title: 'Explore a New Path on Your Wellness Journey',
                        text1: 'Take the first step toward a more balanced life with practical tips and curated resources designed to support every dimension of your well-being—Emotional, Environmental, Financial, Intellectual, Physical, Occupational, Social, and Spiritual.',
                        text2: 'Begin your transformation today!',
                        text3: ''
                      },
                      card1: { title: 'Emotional Wellness', text: 'Learn how to nurture your emotional well-being.' },
                      card2: { title: 'Physical Wellness', text: 'Discover exercises and practices to enhance physical health.' },
                      card3: { title: 'Social Wellness', text: 'Improve your social connections and community involvement.' },
                      cta: { quote: 'Get Started to a Healthier Start Your Wellness Journey Now' }
                    
    },
    contact:{
        hero:{title:'Contact Us' },
        section:{point1:'2200 Hunt St. #415 Detroit, MI 48207',
                point2:'313-403-3900',
                point3:'drlisa@quiltedrose.org'
        },
        phone:{title:''},
        email:{title:''},
    },
    banner:{
        phone:{phone:'313-403-3900'},
        email:{email:'drlisa@quiltedrose.org'},
    },
    footer:{
        address:{title:''},
        phone:{title:''},
        email:{title:''},
    },
    copyright:{
        copyR:{title:'2025', text1:'Quilted Rose Clinical Services-All Rights Reserved'}
    }
}   

export default pages