export const pages = {
    home:{
        hero:{title:'Welcome to Quilted Rose' },
        about:{title:'Meet Dr. Lisa Walker', 
                text1:'I am Dr. Lisa Walker, a psychologist and licensed mental health counselor (LPC) with more than 20 years of experience. I respect the individual as part of the collective community. I believe that healing or mental health treatment cannot occur alone. Black and Indigenous people heal in community.', 
                text2:'I intentionally serve all Black and Indigenous adults with reverence and compassion. I place a special emphasis on emotionally supporting female-identifying persons who work in the creative, health care, mental health and education fields.',
                text3:'I intentionally serve all Black and Indigenous adults with reverence and compassion. I place a special emphasis on emotionally supporting female-identifying persons who work in the creative, health care, mental health and education fields.'},
        vision:{title:'Our Vision', 
                text1:'My vision is to collaborate with Black and Indigenous individuals as we navigate everyday challenges—grief and loss, anxiety, political burnout—along with collective trauma and systemic marginalization. I offer several ways to support and partner with you on this journey:', 
                quote:'“You will be understood and challenged. You will grow and be uncomfortable.” -Dr. Lisa Walker'},
        card1:{title:'Speaking Engagement', 
                text:'With nearly 20 years of clinical experience, Dr. Walker has worked in various leadership roles across various industries in the health care field. '},
        card2:{title:'Professional Coaching', 
                text:'Dr. Walker is dedicated to professional coaching, particularly in clinical supervision (LLPC) and guiding individuals and groups through personal and professional growth.'},
        card3:{title:'Consulting', 
                text:'Providing high-quality training in trauma-informed care, somatic experiencing, and cultural humility, Dr. Walker specializes in clinical training.'},
        cta:{quote:'"You will have breakthroughs and struggle to see progress. I will focus on your strengths even if you do not see any." - Dr. Lisa Walker'},
        belief:{title:'What We Believe', 
                text1:'Quilted Rose was created out of a deep ancestral drive to work inpartnership with Black and Indigenous people as we navigate everyday challenges (grief and loss, anxiety, political burnout), collective trauma and targeted marginalization.',
                text2:'Are you an African, Black American, or Indigenous person looking to incorporate or explore traditional spiritual practices within your mental wellness or coaching journey—in a safe and intentional way?'},
        contact:{title:'Contact'}
    },
    about:{
        hero:{title:'Meet Dr. Lisa Walker' },
        about:{title:'Founder, Consultant, Speaker',
                text1:'I am Dr. Lisa Walker, a psychologist and licensed mental health counselor (LPC) with more than 20 years of experience', 
                text2:'I believe that healing or "mental health treatment" cannot occur alone. Black and Indigenous people heal in community. Quilted Rose was created out of a deep ancestral drive to work in partnership with Black and Indigenous people as we navigate everyday challenges (grief and loss, anxiety, political burnout), collective trauma and targeted marginalization.', 
                text3:'Working with me may include activities to help you understand where emotions are stored in your body and how to release or expand those emotions, referrals to spiritual healers, and may include referrals to professionals that practice typical western medicine.'},
        values:{title:'My Values',
                text1:'I intentionally serve Black and Indigenous adults with reverence and compassion, with a special focus on emotionally supporting female-identifying individuals in creative, healthcare, mental health, and education fields.', 
                text2:'I work collaboratively to foster growth in those affected by cultural trauma, guide adults newly diagnosed with ADHD in their 30s, 40s, and 50s as they navigate this new identity, and support individuals struggling with a complicated relationship with food or movement (disordered eating).', 
                text3:' I offer several ways to support and partner with you on this journey:'},
        card1:{title:'', text:''},
        card2:{title:'', text:''},
        card3:{title:'', text:''},
        cta:{quote:''},
    },
    resources:{
        hero:{title:'Resources', 
              text1:'',
              text2:'',
              text3:'', },
        reads:{title:'Recommended Reads' },
        partners:{title:'Community Partners' },
        books:{point1:'Ain"t I A Woman-Sojourner Truth', 
            point2:'All About Love-Bell Hooks', 
            point3:'Post Traumatic Slave Syndrome -Dr.Joy Degruy', 
            point4:'Women Race and Class-Angela Davis', 
            point5:'Hood Feminism-Mikki Kendall', 
            point6:'Kindred-Octavia E. Butler', 
            point7:'My Grandmother"s Hands-Resmaa Menakem',},
        cta:{quote:''},
    },
    services:{
        hero:{title:'Services'},
        about:{title:'Therapy',
             text1:'Are you an African, Black American, or Indigenous person looking to integrate traditional spiritual practices into your mental wellness or coaching journey in a safe and intentional way?',
             text2:'When working with me, you are welcomed and encouraged to incorporate or explore traditional spiritual practices (Ifa, ancestral veneration, altar building, vision boards, tarot, crystals, essential oils, astrology) into therapy or coaching',
             text3:'Are you an African, Black American, or Indigenous person looking to integrate traditional spiritual practices into your mental wellness or coaching journey in a safe and intentional way?'},
        bullet:{text1:'If you are a non-profit organization, corp or political office seeking:',
                point1:'Guidance', 
                point2:'Burn out prevention & Recovery', 
                point3:'Staff Retention',
                point4:'Guidance', 
                point5:'Burn out prevention & Recovery', 
                point6:'Staff Retention',
                text2:'Take a look below and explore the different ways we can work together.'}, 
        cta:{quote:''},
        other:{title:'Other Ways to Work With Me', 
                text1:'Are you an African, Black American, or Indigenous person looking to integrate traditional spiritual practices into your mental wellness or coaching journey in a safe and intentional way?'},
        contact:{title:''},
        service1:{heading:'Speaking Engagements', subtitle:'With almost 20 years of clinical experience working with individuals and groups. Dr. Walker has worked as a clinician and in leadership positions in private child welfare settings, hospitals, residential, outpatient and criminal justice settings.'},
        service2:{heading:'Professional Coaching', subtitle:'Dr. Walker has nearly 20 years of clinical experience across various settings. She has worked as a clinician and in leadership positions in private child welfare settings, hospitals, residential, outpatient and criminal justice settings. Specializing in professional coaching, particularly in clinical supervision (LLPC), she is now dedicated to guiding individuals and groups through personal and professional growth.'},
        service3:{heading:'Consulting', subtitle:'The consulting petal of Quilted Rose Clinical Services was created to provide high quality training in trauma-informed care, somatic expericing and cultural humility. With a focus on clinical training and corporate DEI consultation, Dr. Walker empowers school systems, child welfare/services agencies, for-profit corporations, and non-profit organizations. Count on her expertise to navigate the unknown, instill resilience, and seamlessly integrate trauma-informed principles into your organization.'},
        service4:{heading:'', subtitle:''},
    },
    privacy:{
        hero:{title:'' },
        section1:{title:'', text:''},
        policy:{title:'', text:''},
        policy1:{title:'', text:''},
        policy2:{title:'', text:''},
        policy3:{title:'', text:''},
        policy4:{title:'', text:''},
        policy5:{title:'', text:''},
        policy6:{title:'', text:''},
    },
    faq:{
        hero:{title:'Frequently Asked Questions' },
        header:{title:'Before Getting Started with Quilted Rose', text1:'Take a look at our FAQ below:'},
        faq1:{heading:'What is the length and frequency of our sessions?', subtitle:'50 minutes typically once a week'},
        faq2:{heading:'Are the sessions virtual or in person?', subtitle:'All sessions are virtual'},
        faq3:{heading:'Do you bill insurance?', subtitle:'We no longer accept any form of insurance. All payments are due at the time of service.'},
        faq4:{heading:'What are your privacy practices?', subtitle:'Our privacy policy can be found here.'},
        cta:{quote:''},
    },
    contact:{
        hero:{title:'Contact Us' },
        section:{point1:'2200 Hunt St. #415 Detroit, MI 48207',
                point2:'313-403-3900',
                point3:'drlisa@quiltedrose.org'
        },
        phone:{title:''},
        email:{title:''},
    },
    banner:{
        phone:{phone:'313-403-3900'},
        email:{email:'drlisa@quiltedrose.org'},
    },
    footer:{
        address:{title:''},
        phone:{title:''},
        email:{title:''},
    },
}   